version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      -8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      3307:3306
  environment:
      MYSQL_DATABASE: newdbs
      MYSQL_USER: aniket
      MYSQL_PASSWORD: Aniket@9867
      MYSQL_ROOT_PASSWORD: Aniket@9867